### ISSUE TITLE
`custom-rules` plugin in core eslint config is unpublished (or misconfigured)

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#3725]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

I'm now seeing the error:

> An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Environment

- Daffodil version: 0.84.0

### Steps to reproduce

Steps to reproduce:
1. Attempt to use `@daffodil/eslint-config
2. Setup eslint like:

```ts
module.exports = {
  plugins: [
    'modules-newline',
    'jasmine',
    "prefer-arrow"
  ],
  extends: [
    '@daffodil/eslint-config',
  ],
}
```

3. See error

> An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Expected behavior

No error.

### Actual behavior

> > An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Additional context

The offending [line](https://github.com/graycoreio/daffodil/blob/develop/tools/eslint/config/index.js#L11). Likely caused by #3639 from @leozhang14
