### PR TITLE
chore(design): move custom daff docs rule plugin into design

### LINKED ISSUE #3725: `custom-rules` plugin in core eslint config is unpublished (or misconfigured)
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

I'm now seeing the error:

> An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Environment

- Daffodil version: 0.84.0

### Steps to reproduce

Steps to reproduce:
1. Attempt to use `@daffodil/eslint-config
2. Setup eslint like:

```ts
module.exports = {
  plugins: [
    'modules-newline',
    'jasmine',
    "prefer-arrow"
  ],
  extends: [
    '@daffodil/eslint-config',
  ],
}
```

3. See error

> An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Expected behavior

No error.

### Actual behavior

> > An unhandled exception occurred: Failed to load plugin 'custom-rules' declared in 'projects/my-app/.eslintrc.js » ../../.eslintrc.js#overrides[0] » ./projects/eslint/index.js » @daffodil/eslint-config': Cannot find module 'eslint-plugin-custom-rules'

### Additional context

The offending [line](https://github.com/graycoreio/daffodil/blob/develop/tools/eslint/config/index.js#L11). Likely caused by #3639 from @leozhang14

### PR DESCRIPTION
**Pull request by xelaint**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #3725

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Review by damienwebdev — APPROVED** [review]
lgtm
